linters:
  enable:
    - depguard
    - gofumpt
    # - copyloopvar
    - unconvert
    - unparam

linters-settings:
  depguard:
    rules:
      all:
        allow: []
        deny:
          - pkg: log
            desc: use zerolog

          - pkg: github.com/rs/zerolog/log
            desc: use context logger
