linters:
  enable:
    - depguard
    - exportloopref
    - gofumpt
    - unconvert
    - unparam

linters-settings:
  depguard:
    rules:
      all:
        allow: []
        deny:
          - pkg: log
            desc: use zerolog
