name: Build project
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - uses: extractions/setup-just@v1

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - run: just build
