name: golangci-lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
